### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by neuromancer** [Palm-Studios/sh3redux#1]
I was wondering if Linux support is planned.

Thanks!

**Comment by Quaker762** [comment]
Hi,

Most certainly. I'm trying to write code as platform independent as possible (see stdtype.hpp, though it's very basic). If you know anything about Linux programming, please by all means make a Pull Request!!

**Comment by elken** [comment]
I can maybe chip in in a week or so.

**Comment by thagabe** [comment]
Vulkannnnnn

**Comment by Sonderhen** [comment]
Quaker762 you have a e-mail contact? I need to talk to you.

**Comment by z33ky** [comment]
I believe this is taken care of.
@Quaker762 close?

**Comment by Quaker762** [comment]
@z33ky Yep, I think this has been _thoroughly_ taken care of by now :)
