### ISSUE TITLE
Documentation extraction

### ISSUE THREAD

**Issue by z33ky** [Palm-Studios/sh3redux#18]
There seems to be a well defined inline-documentation format via code comments for files and functions.
I'm not familiar with it; is there a tool ala Doxygen to extract it?

I'd also like to question the "revision history" part of the documentation. It's easy to get out of date - instead one can use `git log $FILE` (maybe with `--oneline`) to get one and then one can also easily check the specific code changes made via `git show`.

**Comment by Quaker762** [comment]
At the moment I've been using a mixture between the old Microsoft NT4 comment style, as well as Dreamworks Interactives header/comment style (Trespasser is one of the most well documented pieces of software I've ever seen), so there is not application to extract it. 

Seeing as this will probably get more serious, do you recommend we switch to a more standard comment style, or should I just write a tool to extract it?

**Comment by z33ky** [comment]
Doxygen is certainly widely used and I see little reason to take on the effort to write a competing piece of software. Doxygen also has a rather widely known style, which reduces friction for new contributors.
I'll convert one file to Doxygen-style comments later today so you can check it out.

**Comment by z33ky** [comment]
Alright you can checkout [z33ky/sh3redux@doxygen](/z33ky/sh3redux/tree/doxygen).
The [Doxyfile](/z33ky/sh3redux/tree/doxygen/Doxyfile) is autogenerated by `doxygen -g` and merged with some old Doxyfile of another project of mine.
I've converted [include/SH3/arc/types.hpp](/z33ky/sh3redux/tree/doxygen/include/SH3/arc/types.hpp) partially do Doxygen; the classes are not fully documented.
To generate HTML just execute `doxygen` in the project root and you can direct your browser to `docs/html/index.html`.

**Comment by z33ky** [comment]
Just as a heads-up: This is being worked on. Doxygen is used now. As soon as all headers are switched to Doxygen-style I'll commit a Doxyfile and integrate it into the CMake build system.

The next step then is to move the .cpp documentation to the headers and finally ensure that all relevant things are documented.
Doxygen can warn about undocumented stuff, but this cannot be fine tuned so we will have to document every function and every member then. Not necessarily the worst option, but debatable.

**Comment by Quaker762** [comment]
It would seem that this has been taken care of.
