### ISSUE TITLE
exit() and return from main()

### ISSUE THREAD

**Issue by z33ky** [Palm-Studios/sh3redux#53]
As pointed out in #50, calling `exit()` from `main()` does not run destructors.
This could result in unexpected behaviour. Same with `die()` and `assert()` if you think about it; any objects on the stack will not have their destructor called.

Files are flushed and closed by the runtime before exiting, so nothing will get lost there. If any logging is done in the destructors of objects, that will be missing though.
Other visible effects would involve IPC that is not done through files? Plus again any IPC done in destructors.

This is probably not as significant for `die()` and `assert()`, which are for abnormal termination anyways. Still, there are alternatives: we could never use these and instead use error-codes everywhere. Seems a bit excessive for exceptional situations IMO.
We could throw exceptions, which unwind the stack and call destructors.

For `main()`, if we want to have the destructors of the local variables called there are a bunch of things we can do.
We could just `return static_cast<int>(error_code::*);`, which is a little longer, but we won't have to write it often anyways.
We could let `main()` just forward to another `sh_main()` function, `main()` not having any objects on the stack at all.
We could also wrap everything except the `exit()` call in another scope, like so:
```
int main()
{
    error_code code = error_code::SUCCESS;
    {
        //...
    }
    exit(code);
}
````
Which is more or less the same as the previous suggestion.

I think it makes sense to just `static_cast`.
For `die()` we should perhaps stick a `@warn` in the documentation that destructors will not be run on objects on the stack. We can also replace `assert()` with a custom variant, which also tries to log the assertion, and perhaps supports stuff like continuing anyways, for purpose of debugging.

**Comment by z33ky** [comment]
I forgot, for `main()` we can also change from a `enum class` for `error_code` to a plain `enum`, though we'd loose the mandatory scoping. There are workarounds to make something that looks like a scoped `enum` though, with namespaces or inconstructible classes.

**Comment by Quaker762** [comment]
> I think it makes sense to just static_cast.

I like this as well. As good as having an `sh_main` function would be, that would probably just confuse anyone else looking to join, as they'd have to go 'function hunting'

> For die() we should perhaps stick a @warn in the documentation that destructors will not be run on objects on the stack. We can also replace assert() with a custom variant, which also tries to log the assertion, and perhaps supports stuff like continuing anyways, for purpose of debugging.

I agree. For the most part though, die doesn't necessarily _need_ to run destructors for stack objects, as the shit has already hit the fan. As for the custom assert(), I feel later in development this will make debugging a LOT easier.

**Comment by z33ky** [comment]
> As for the custom assert(), I feel later in development this will make debugging a LOT easier.

I'm working on it. I'll open a pull request after I got some sleep and cleaned it up.
This issue is done though.
