### ISSUE TITLE
Random questions to the developers

### ISSUE THREAD

**Issue by eblanca** [Palm-Studios/sh3redux#85]
This is a very nice project, well done guys!
Q1: are you aware of any similar project working on Silent Hill 1/2 ? (I would die for...)
Q2: did you evaluate creating an engine for ResidualVM instead of a stand-alone project ? It is a nice multi-platform portable application (with a solid user base), so I can figure out it as a safe place to raise a new 3d game engine into.

**Comment by Quaker762** [comment]
Hi, 

> Q1: are you aware of any similar project working on Silent Hill 1/2 ? (I would die for...)

No, but literally everyone that hears about this wants SH2 to be done. The engines are _very_ similar, however there are a few differences between formats. When this is done we can just fork sh3redux and maybe do sh2redux. SILENT HILL 1 I have no idea about though, there isn't as much of a modding scene as far as I can tell. (I'd definitely love to do SH2, it was the first one I played, I just like the atmosphere of 3 more haha)

> Q2: did you evaluate creating an engine for ResidualVM instead of a stand-alone project ? It is a nice multi-platform portable application (with a solid user base), so I can figure out it as a safe place to raise a new 3d game engine into.

ResidualVM isn't an Engine. It's an interpreter to play script based Lucasarts games (similar to ScummVM I assume). That, and it would be fairly difficult to use a pre-existing engine. There is a _serious_ symbiotic relationship between the assets in SILENT HILL 3 and the engine that it runs on. It's easier to just load all the data and send it to the graphics card and make your own documentation than rely on semantics created by someone else.

Cheers, 
Jesse

**Comment by eblanca** [comment]
Thank you.
