### ISSUE TITLE
Weird input into vfile

### ISSUE THREAD

**Issue by Quaker762** [Palm-Studios/sh3redux#86]
I'm getting weird values in the color palette of `sys_konami.tex` (section `pic.arc`, directory offset `0xE10`, file offset `0x56C3E80`). For some reason it's adding a few values of `0x0D` in there? I'm not sure if this is due to the `vfile` buffer, or whether the problem lies in `sh3_arc::LoadFile`

[Here's the problem](http://imgur.com/a/OVZhn), I'm stumped as to why this is happening..

I can confirm that `Dump2Disk()` isn't the issue, as the palette I'm dumping also contains the rogue values.

**Comment by z33ky** [comment]
Are you certain it's not `Dump2Disk()`? It looks like `out_file` should be opened in binary mode (`std::ios_base::binary`).
How are you dumping the palette?

**Comment by Quaker762** [comment]
>  It looks like out_file should be opened in binary mode (std::ios_base::binary).

It looks like that was what was causing the bytes to be inserted in both the palette and `Dump2Disk()`. What causes the `ofstream` to insert these bytes when it isn't opened as binary??

**Comment by z33ky** [comment]
Well, this is exactly what opening a file without the binary flag does. It converts the plain newline character to the system's newline, which on Windows includes a carriage return character.
