### ISSUE TITLE
Arc extraction produces wong output

### ISSUE THREAD

**Issue by z33ky** [Palm-Studios/sh3redux#91]
The files fontdata_j.bin and fontdata_k.bin seem to be extracted incorrectly, as mentioned in #84:
> You have something wrong with arc file management. It looks like it adds extra bytes, even size of file is bigger.

Side-note: Sorry I've been quiet lately. My bachelor's thesis is due in a month and the days suddenly seem to pass quicker than usual...

**Comment by Quaker762** [comment]
> The files fontdata_j.bin and fontdata_k.bin seem to be extracted incorrectly, as mentioned in #84:

I wonder what's causing this.. As far as we've been aware, there's been no problems with dumping textures or anything.. Maybe one of the sections is getting clobbered or it's a problem with my Dump2Disk() (with my janky C++ this is VERY likely haha)

> Side-note: Sorry I've been quiet lately. My bachelor's thesis is due in a month and the days suddenly seem to pass quicker than usual...

No problem, whenever you have time. All my engineering subjects are sucking my time, and with five units I barely have time to even look at the code for this :(

**Comment by Quaker762** [comment]
This has now been fixed by #96 Dump2Disk was _not_ opening the file in `std::ios::binary` mode.
